language: cpp
sudo: false
matrix:
  include:
    - env:
      - PYTHON_VER='3.7'
      - MAX_DET_ORB=64

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
#  - conda update -q conda
  - conda create -q -n tenv python=$PYTHON_VER gcc_linux-64 gxx_linux-64 gfortran_linux-64 cmake mkl-devel psi4 psi4-dev ci-psi4 pybind11-headers -c psi4/label/dev
  - source activate tenv
  
before_script:
  - python -V
#  - psi4 --version
#  - psi4 --plugin-compile
  - cd ${TRAVIS_BUILD_DIR}
  - >
      cmake -H. -B.
      -C${HOME}/miniconda/envs/tenv/share/cmake/psi4/psi4PluginCache.cmake
      -DCMAKE_BUILD_TYPE=Debug 
      -DPYTHON_EXECUTABLE=${HOME}/miniconda/envs/tenv/bin/python
  - make -j2
  - export PYTHONPATH="${HOME}/build/evangelistalab:$PYTHONPATH"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - python mf.py
